### PR TITLE
Move stageReady so AppMenu will work

### PR DESCRIPTION
**Pull request by corpuscle**
This took a lot of tracking down so I have kept this minimal.

I note that apps based on enyo bootplate don't create their Application object until they receive stageReady. I suppose this change achieves much the same thing.

### CODE REVIEW

**Comment by Herrie82** [comment]
Looking good! We dropped Cordova for most others already before, so no problem in doing that there too. You might want to add an option for your tests to the app menu as well?

**Comment by corpuscle** [comment]
Yeah, that was already in the pipeline.
Try it now:
On-device, use menu not drag to change panels, run tests only on demand and use a cookie to remember your last choice of calculator style (to avoid irritation).

**Comment by corpuscle** [comment]
Now also shows when the memory is active.
Then I got cocky and marked the most straightforward GUI strings for i18n. Git punished me when I got that wrong and tried to do a git commit --amend between pushes to GitHub. I sorted it out but the commit history is a little chaotic.

**Comment by Herrie82** [comment]
Looking good!

**Pull request merged**
